---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podresourcemonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podresourcemonitor
  template:
    metadata:
      labels:
        app: podresourcemonitor
    spec:
      containers:
        - name: podresourcemonitor
          image: yourregistry/podresourcemonitor:v1.0
          command: ["./podresourcemonitor"]
          args: ["-namespace=default", "-pod-label=app=myapp"]
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"