# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ "created" ]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4.1.0
      with:
        go-version: 1.20.5

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  
  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')  
    runs-on: ubuntu-latest
    steps:
    - name: Publish module
      run: GOPROXY=proxy.golang.org go list -m github.com/sfotiadis/broadcast@v${GITHUB_REF#refs/tags/v}